apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: online-shop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sivaprasadpappala/OnlineShoppingGitops.git
    targetRevision: main
    path: apps/online-shop

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true